# Generated by Django 5.0.1 on 2024-01-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Uncategorized', 'Uncategorized')], default='Electronics', max_length=255),
        ),
    ]
