# Generated by Django 5.0.1 on 2024-01-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('jewelry', 'Jewelery'), ('mens_clothing', 'Mens Clothing'), ('womens_clothing', 'Womens Clothing'), ('Uncategorized', 'Uncategorized')], default='electronics', max_length=255),
        ),
    ]
